config/routes.rb
Rails.application.routes.draw do

  get '/terca' => 'home#ter'
  get '/quarta' => 'home#quar'
  get '/quinta' => 'home#quin'
  get '/sexta' => 'home#sex' 

  get 'dash'        => 'pages#dashboard'  
  get '/pages/new'  => 'pages#create'
  root 'pages#dashboard'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users 
  resources :dinners
  resources :lunches

end

app/models/dinner.rb
class Dinner < ActiveRecord::Base
	scope :week, -> { where( :date => Date.today.at_beginning_of_week..Date.today.at_end_of_week - 2) } 

  validates :date, presence: true

end

app/models/lunch.rb
class Lunch < ActiveRecord::Base
  scope :week, -> { where( :date => Date.today.at_beginning_of_week..Date.today.at_end_of_week - 2) } 

  validates :date, presence: true 

end

app/models/user.rb
class User < ActiveRecord::Base

   enum role: [:user, :ad, :nutri, :admin]
   after_initialize :set_default_role, :if => :new_record?

   def set_default_role
     self.role ||= :user
   end

   # [ 0 1 2 3]

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit

  protect_from_forgery with: :exception

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :role) }
  end

  private 
   def user_not_authorized
      flash[:alert] = "Acess denied."
      redirect_to (request.referrer || root_path)
   end
end

app/controllers/dinners_controller.rb
class DinnersController < ApplicationController

  before_action               :authenticate_user!, only: [:create, :update, :edit]
  before_action :set_dinner, only: [:show, :edit, :update, :destroy]

  def index
    @dinners = Dinner.week
  end

  def show
  end

 
  def new 
    authorize User
    @dinner = Dinner.new 
  end


  def edit
        authorize User
  end

  def create

    authorize User
    @dinner = Dinner.new(dinner_params)

    respond_to do |format|
      if @dinner.save
        format.html { redirect_to @dinner, notice: 'Dinner was successfully created.' }
        format.json { render :show, status: :created, location: @dinner }
        format.js
      else
        format.html { render :new }
        format.json { render json: @dinner.errors, status: :unprocessable_entity }
      end
    end
  end

 
  def update
    respond_to do |format|
      if @dinner.update(dinner_params)
        format.html { redirect_to @dinner, notice: 'Dinner was successfully updated.' }
        format.json { render :show, status: :ok, location: @dinner }
      else
        format.html { render :edit }
        format.json { render json: @dinner.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def destroy
        authorize User
    @dinner.destroy
    respond_to do |format|
      format.html { redirect_to dinners_url, notice: 'Dinner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_dinner
      @dinner = Dinner.find(params[:id])
    end

 
    def dinner_params
      params.require(:dinner).permit(:date, :soup, :accompaniment1, :accompaniment2, :accompaniment3, :garnish, :protein1, :protein2, :dessert, :juice)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/lunches_controller.rb
class LunchesController < ApplicationController

  before_action               :authenticate_user!, only: [:create, :update, :edit, :new]
  before_action :set_lunch, only: [:show, :edit, :update, :destroy]

  def index 
    @lunches = Lunch.week
  end

  def show
  end

 
  def new
    authorize User
    @lunch = Lunch.new
  end


  def edit
      authorize User
  end

  def create
    authorize User
    @lunch = Lunch.new(lunch_params)

    respond_to do |format|
      if @lunch.save
        format.html { redirect_to @lunch, notice: 'Lunch was successfully created.' }
        format.json { render :show, status: :created, location: @lunch }
        format.js
      else
        format.html { render :new }
        format.json { render json: @lunch.errors, status: :unprocessable_entity }
      end
    end
  end

 
  def update
    authorize User
    respond_to do |format|
      if @lunch.update(lunch_params)
        format.html { redirect_to @lunch, notice: 'Lunch was successfully updated.' }
        format.json { render :show, status: :ok, location: @lunch }
      else
        format.html { render :edit }
        format.json { render json: @lunch.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def destroy
    authorize User
    @lunch.destroy
    respond_to do |format|
      format.html { redirect_to lunches_url, notice: 'Lunch was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_lunch
      @lunch = Lunch.find(params[:id])
    end

 
    def lunch_params
      params.require(:lunch).permit(:date, :protein1, :protein2, :protein3, :accompaniment1,
		 :accompaniment2, :accompaniment3,:salad1, :salad2, :salad3, :garnish, :dessert, :juice)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  before_action               :authenticate_user!, except: [:dashboard]  

  def index
    if current_user
      redirect_to dash_path
    end
  end

  def dashboard
    @dinners      = Dinner.where( :date => Date.today.at_beginning_of_week..Date.today.at_end_of_week - 2)
    @dinner_today = Dinner.where(date: Date.today)
    @lunches      = Lunch.where( :date => Date.today.at_beginning_of_week..Date.today.at_end_of_week - 2) 
    @lunch_today  = Lunch.where(date: Date.today)
  end

  def create
    authorize User
    @dinner = Dinner.new
    @lunch  = Lunch.new 
  end
end

app/controllers/users_controller.rb
class User::RegistrationsController < Devise::RegistrationsController

  def create
    redirect_to root_path if Rails.env.production?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def javascript(*files)
      content_for(:head) { javascript_include_tag(*files) }
    end

  def stylesheet(*files)
    content_for(:head) { stylesheet_link_tag(*files) }
  end
end

app/helpers/dinners_helper.rb
module DinnersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lunches_helper.rb
module LunchesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/dinners/_dinner.html.erb
<%= form_for(@dinner, remote: true) do |f| %>
<div class="form-group">
  <%= f.label :date %>
  <%= f.date_field :date, class: "form-control date" %>
</div>

<div class="form-group">
  <%= f.label :soup %>
  <%= f.text_field :soup, class: "form-control soup" %>
</div>

<div class="form-group">
  <%= f.label :accompaniment1 %>
  <%= f.text_field :accompaniment1, class: "form-control accompaniment1"   %>
</div>


<div class="form-group">
  <%= f.label :accompaniment2 %>
  <%= f.text_field :accompaniment2, class: "form-control accompaniment2"   %>
</div>


<div class="form-group">
  <%= f.label :accompaniment3 %>
  <%= f.text_field :accompaniment3, class: "form-control accompaniment3"   %>
</div>


<div class="form-group">
  <%= f.label :garnish %>
  <%= f.text_field :garnish, class: "form-control garnish"   %>
</div>


<div class="form-group">
  <%= f.label :protein1 %>
  <%= f.text_field :protein1, class: "form-control protein1"   %>
</div>


<div class="form-group">
  <%= f.label :protein2 %>
  <%= f.text_field :protein2, class: "form-control protein2"   %>
</div>


<div class="form-group">
  <%= f.label :protein3 %>
  <%= f.text_field :protein3, class: "form-control protein3"   %>
</div>

<div class="form-group">
  <%= f.label :dessert %>
  <%= f.text_field :dessert, class: "form-control dessert"   %>
</div>


<div class="form-group">
  <%= f.label :juice %>
  <%= f.text_field :juice, class: "form-control juice"   %>
</div>

<div class="form-group">
  <%= f.submit  %>
</div>

<% end %>
<%= link_to 'Back', :back %>

app/views/dinners/_form.html.erb
<div id="container_dinners">
<%= form_for(@dinner, remote: true, html: {id: "registerDinner", autocomplete: "off"}) do |f| %>
<div class="row">
  <div class="col-md-6">
     <div class="form-group">
  <%= f.label :date, 'Data:' %>
  <%= f.date_field :date, class: "form-control date" %>
</div>

<div class="form-group">
  <%= f.label :soup, 'Sopa:' %>
  <%= f.text_field :soup, class: "form-control soup", list: "soup" %>
</div>

<datalist id="soup">

  <option value="CANJA">
  <option value="CANJIQUINHA">
  <option value="CANJIQUINHA AO MOLHO">
  <option value="DELÍCIA">
  <option value="MINEIRA">
  <option value="POLENTA AO MOLHO">
  <option value="SOPA DE GRÃO DE BICO">
  <option value="SOPA DE LEGUMES">  
  <option value="SOPA DE LEGUMES COM MACARRÃO">
  <option value="SOPA DE LENTILHA">
  
</datalist>

<div class="form-group">
  <%= f.label :accompaniment1, 'Acompanhamento 1:' %>
  <%= f.text_field :accompaniment1, class: "form-control accompaniment1" %>
</div>

<div class="form-group">
  <%= f.label :accompaniment2, 'Acompanhamento 2:' %>
  <%= f.text_field :accompaniment2, class: "form-control accompaniment2" %>
</div>
      
<div class="form-group">
  <%= f.label :accompaniment3, 'Acompanhamento 3:' %>
  <%= f.text_field :accompaniment3, class: "form-control accompaniment3" %>
</div>

  </div>
  <!-- col-md-6 -->
  <div class="col-md-6">



<div class="form-group">
  <%= f.label :garnish, 'Guarnição:' %>
  <%= f.text_field :garnish, class: "form-control garnish", list: "garnish" %>
</div>

<datalist id="garnish">

  <option value="ABÓBORA SAUTEÉ">
  <option value="BATATA PALHA">
  <option value="CENOURA SAUTÉE">
  <option value="CENOURA VICK">
  <option value="CHUCHU COM SALSA">
  <option value="ESPAGUETE À CARBONARA">
  <option value="ESPAGUETE AO ALHO E ÓLEO">
  <option value="ESPAGUETE AO SUGO">
  <option value="FAROFA">
  <option value="POLENTA">
  <option value="PURÊ DE BATATA">
  <option value="QUIBEBE">

</datalist>

<div class="form-group">
  <%= f.label :protein1, 'Proteína 1:' %>
  <%= f.text_field :protein1, class: "form-control protein1", list: "protein" %>
</div>

<div class="form-group">
  <%= f.label :protein2, 'Proteína 2:' %>
  <%= f.text_field :protein2, class: "form-control protein2", list: "protein" %>
</div>

<datalist id="protein">

  <option value="ALMÔNDEGAS AO MOLHO DE CALABRESA">
  <option value="ALMÔNDEGAS DE CARNE">
  <option value="ALMÔNDEGAS DE FRANGO">
  <option value="ALMÔNDEGAS DE SOJA">

  <option value="BIFE DE FÍGADO BOVINO">
  <option value="BIFE SUÍNO">
  <option value="BOLINHO DE GRÃO DE BICO">

  <option value="CARNE MISTA">
  <option value="CARNE MOÍDA DE SOJA">
  <option value="CARRÉ">
  <option value="COSTELA COM AGRIÃO">
  <option value="COSTELA COM BATATA">
  <option value="COXA E SOBRECOXA">
  <option value="CUBOS DE FRANGO">

  <option value="ESTROGONOFE DE CARNE">
  <option value="ESTROGONOFE VEGETARIANO">

  <option value="FÍGADO">
  <option value="FÍGADO À LISBOETA">
  <option value="FILÉ DE FRANGO À MILANESA">
  <option value="FILÉ DE FRANGO GRELHADO">  
  <option value="FRANGO ASSADO">
  <option value="FRANGO ENSOPADO">
  <option value="FRANGO XADREZ">
  <option value="FRICASSÊ DE FRANGO">

  <option value="GOULASH">

  <option value="HAMBÚRGUER DE SOJA">

  <option value="ISCA BOVINA ACEBOLADA">
  <option value="ÍSCA DE FRANGO">
  <option value="ÍSCA DE FRANGO ACEBOLADA">
  
  <option value="KIBE DE SOJA">
  <option value="KIBE DE ABÓBORA">

  <option value="LASANHA DE BERINJELA">  
  <option value="LINGUIÇA TOSCANA">

  <option value="MEXIDO DE OVOS">
  <option value="MOELA COM BATATA">
  <option value="MOLHO DE CACHORRO QUENTE">
  
  <option value="OMELETE">
  <option value="OVOS MEXIDOS">

  <option value="PANQUECA DE FRANGO">
  <option value="PANQUECA DE SOJA">
  
  <option value="QUIBE DE SOJA">
  <option value="QUICHE DE MILHO">

  <option value="SASSAMI EMPANADO AO MOLHO DE MOSTARDA">
  <option value="STEAK DE FRANGO">
  <option value="SUFLÊ DE CENOURA">
  <option value="SUFLÊ DE LEGUMES">
  <option value="SUÍNO ASSADO AO MOLHO">

  <option value="TORATA DE BATATA COM CARNE MOÍDA">
  <option value="TORTA DE CEBOLA">
  <option value="TORTA DE FRANGO">

  <option value="VIRADO A PAULISTA">

</datalist>

<div class="form-group">
  <%= f.label :dessert, 'Sobremesa:' %>
  <%= f.text_field :dessert, class: "form-control dessert", list: "dessert" %>
</div>

<datalist id="dessert">
  
  <option value="BANANA">
  <option value="DOCE">
  <option value="DOCE DE LEITE">
  <option value="DOCE INDIVIDUAL">
  <option value="FRUTA">
  <option value="GELATINA BICOLOR">
  <option value="GELATINA COM LETE CONDENSADO">
  <option value="GELÉIA CLORIDA">
  <option value="LARANJA">
  <option value="MANJAR DE COCO">
  <option value="MELANCIA">
  <option value="MELÃO">
  <option value="PAÇOCA">
  <option value="PÉ DE MOLEQUE">
  <option value="PUDIM">
  <option value="PUDIM DE BAUNILHA">
  <option value="PUDIM DE CARAMELO">

</datalist>

<div class="form-group">
  <%= f.label :juice, 'Suco:' %>
  <%= f.text_field :juice, class: "form-control juice", list: "juice" %>
</div>

<datalist id="juice">

  <option value="ABACAXI">
  <option value="GOIABA">
  <option value="GUARANÁ">
  <option value="LARANJA">
  <option value="LIMÃO">
  <option value="MANGA">
  <option value="UVA">

</datalist>

<div class="form-group">
</div>
  </div>
  <!-- col-md-6 -->
 </div>

<div class="row">
  <div class="col-md-6 btn-wrapper">
      <%= link_to 'Voltar', :back, class:'btn btn-warning control-btn', role:'button', method: :get %>
  </div>
  <div class="col-md-6 btn-wrapper">
      <div class="form-group">
    <%= f.submit 'Salvar', class: "btn btn-primary control-btn" %>
  </div>
  </div>
</div>
<% end %>
</div>

app/views/dinners/create.js.erb
$(".date").val('');
$(".soup").val('');
$(".accompaniment1").val('ARROZ BRANCO');
$(".accompaniment2").val('FEIJÃO');
$(".accompaniment3").val('ARROZ INTEGRAL');
$(".protein1").val('');
$(".protein2").val('');
$(".protein1").val('');
$(".dessert").val('');
$(".juice").val('');

swal("Jantar Cadastrado!");
$("#container_dinners").replace('<%= j render "form" %>');

app/views/dinners/edit.html.erb
<%= render 'form' %>

app/views/dinners/index.html.erb
<table class="table table-striped custab">
    <thead>
    
        <tr>
            <th>Date</th> 
            <th class="text-center">Action</th>
        </tr>
    </thead>
    <tbody>

        <% @dinners.each do |dinner| %>
            <tr>
                <td><%= link_to dinner.date, dinner %></td> 
                <td class="text-center">
                <%= link_to '<span class="glyphicon glyphicon-edit"></span> Edit'.html_safe, edit_dinner_path(dinner), :class => "btn btn-info btn-xs" %>
                <%= link_to '<span class="glyphicon glyphicon-remove"></span>Delete'.html_safe, dinner_path(dinner) , method: :delete ,data: { confirm: "Are you sure you want to delete this dinner?"}, class: "btn btn-danger btn-xs" %>
                </td>
            </tr>
          <% end %>

    </tbody>
</table>
<%= link_to '+ New Dinner', new_dinner_path, class: "btn btn-primary btn-xs pull-right" %>

app/views/dinners/new.html.erb
<%= render 'form' %>

app/views/home/index.html.erb
<div class="container space-top">

<%= render 'layouts/navday' %>       

<div class="bs-example bs-example-tabs" data-example-id="togglable-tabs"> 
  <ul id="myTabs" class="nav nav-tabs" role="tablist"> 
    <li role="presentation" class="active">
      <a href="#home" id="home-tab" role="tab" data-toggle="tab" aria-controls="home" aria-expanded="true">ALMOÇO</a>
    </li> 
    <li role="presentation" class="">
      <a href="#profile" role="tab" id="profile-tab" data-toggle="tab" aria-controls="profile" aria-expanded="false">JANTAR</a>
      </li>  
   </ul> 
     <div id="myTabContent" class="tab-content"> 
       <div role="tabpanel" class="tab-pane fade active in" id="home" aria-labelledby="home-tab"> 


        <div class="container custom" data-example-id="striped-table">
				<table class="table table-striped"> 
					<thead> 
						<tr> 
							<th></th>							
							<th>Segunda-Feira - 21/03/2016</th> 
						</tr> 
					</thead> 
					<tbody> 
						<tr> 
							<th scope="row">SALADA 1</th> 
							<td>SALADA DE FOLHAS</td> 
							
						</tr> 
						<tr> 
							
							<th scope="row">SALADA 2</th>  
							<td>TABULE</td> 
							 
						</tr> 
						<tr> 
							<th scope="row">ACOMPANHAMENTO1</th> 
							<td>ARROZ BRANCO</td> 							
						</tr>
						<tr>
							<th scope="row">ACOMPANHAMENTO2</th>
							 <td>FEIJÃO PRETO</td>
						</tr> 
						<tr>
							<th scope="row">ACOMPANHAMENTO3</th>
							<td>ARROZ INTEGRAL</td> 
						</tr> 
						<tr>
							<th scope="row">GUARNIÇÃO</th>
							<td>FAROFA</td> 
						</tr> 
						<tr>
							<th scope="row">PROTEÍNA1</th>
							<td>LINGUIÇA TOSCANA</td> 
						</tr> 
						<tr>
							<th scope="row">PROTEÍNA2</th>
							<td>TORTA DE FRANGO</td> 
						</tr>
						<tr>
							<th scope="row">PROTEÍNA3</th>
							<td>CARNE MOÍDA DE SOJA</td> 
						</tr>
						<tr>
							<th scope="row">SOBREMESA</th>
							<td>DOCE DE LEITE</td> 
						</tr>
						<tr>
							<th scope="row">SUCO</th>
							<td>GOIABA</td> 
						</tr>
					</tbody> 
				</table> 
			</div>


      </div> 
      <div role="tabpanel" class="tab-pane fade" id="profile" aria-labelledby="profile-tab"> 
      <p class='text-center'><i>obs: O RU está em acordo com a reitoria para saber se haverá jantar</i></p>
        <div class="container custom" data-example-id="striped-table"> 
				<table class="table table-striped"> 
					<thead> 
						<tr> 
							<th></th>
							<th>Segunda-Feira - 21/03/2016</th>
						</tr> 
					</thead> 
					<tbody> 
						<tr> 
							<th scope="row">SOPA</th> 
							<td>SOPA DE LENTILHA</td> 
							
						</tr>   
						<tr> 
							<th scope="row">ACOMPANHAMENTO1</th> 
							<td>ARROZ BRANCO</td> 							
						</tr>
						<tr>
							<th scope="row">ACOMPANHAMENTO2</th>
							 <td>FEIJÃO PRETO</td>
						</tr> 
						<tr>
							<th scope="row">ACOMPANHAMENTO3</th>
							<td>ARROZ INTEGRAL</td> 
						</tr> 
						<tr>
							<th scope="row">GUARNIÇÃO</th>
							<td>FAROFÁ</td> 
						</tr> 
						<tr>
							<th scope="row">PROTEÍNA1</th>
							<td>COSTELA COM BATATA</td> 
						</tr> 
						<tr>
							<th scope="row">PROTEÍNA2</th>
							<td>OMELETE</td> 
						</tr> 
						<tr>
							<th scope="row">SOBREMESA</th>
							<td>BANANA</td> 
						</tr>
						<tr>
							<th scope="row">SUCO</th>
							<td>ABACAXI</td> 
						</tr>
					</tbody> 
				</table> 
			</div>




      </div>


  </div>
 </div>

app/views/layouts/_footer.html.erb
<footer>
      <a href="http://site.soulcodejr.com" target="_blank"><%= image_tag "sclogo.png", alt: "Logo da Soul Code", class: "img-responsive" %></a>
      <small>Todos os direitos reservados à Soul Code</small>
</footer>

app/views/layouts/_metatags.html.erb
<meta name="keywords" content="RU UENF, UENF, Bandejao, Bandejão RU, Restaurante Universitário UENF"> 
<meta name="author" content="SoulCode">
<meta name=”description” content=”O site foi desenvolvido com o intuito de trazer mais comodidade a comunidade UENFiana”>
<meta name="viewport" content="width=device-width, initial-scabe=1.0">

app/views/layouts/_nav.html.erb
<div class="navbar navbar-default navbar-fixed-top">
	<%= link_to root_path, method: :get do %>
	<%= image_tag "logo.png", alt: "Logo", class: "img-responsive header-logo" %>
	<% end %>
	<!-- Trigger the modal with a button -->
	<% if !current_page?(root_path) && current_user.nil?  %>
	<button type="button" class="btn btn-info btn-lg btn-login b-login" data-toggle="modal" data-target="#myModal">Login</button>
	<% end %>
	
	<ul class="nav-list">

		<li><%= link_to 'HOME', root_path, method: :get %></li>
		<li><a href="javascript:void(0)">SUGESTÃO</a></li>
		<% unless current_user.nil? %>
			<div class="desktop-nav">
				<li><%= link_to 'Cadastrar', pages_new_path, method: :get %></li>
				<li><%= link_to 'Editar Almoço', lunches_path %></li>
				<li><%= link_to 'Editar Jantar', dinners_path %></li>
				<li><%= link_to '<i class="fa fa-sign-out"></i> Sair'.html_safe , destroy_user_session_path, method: :delete %></li>
			</div>
		<% end %>
		<li class="responsive-nav">
		<% unless current_user.nil? %>
			<div class="dropdown">
				<button class="btn btn-primary dropdown-toggle nav-menu" type="button" data-toggle="dropdown">MENU
					<i class="fa fa-caret-down"></i>
				</button>
				<ul class="dropdown-menu" id="nav-drop-menu">
					

					<li><%= link_to 'Cadastrar', pages_new_path, method: :get %></li>
					<li><%= link_to 'Editar Almoço', lunches_path %></li>
					<li><%= link_to 'Editar Jantar', dinners_path %></li>
					<li><%= link_to '<i class="fa fa-sign-out"></i> Sair'.html_safe , destroy_user_session_path, method: :delete %></li>
					
				</ul>
			</div>
		<% end %>			
		</li>


			</ul>
		</div>
	</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Restaurante Universitário - UENF</title>
  <%= render 'layouts/metatags' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= analytics_init if GoogleAnalytics.valid_tracker? %>
  <%= csrf_meta_tags %>

</head>
<body>
  <%= render "layouts/nav" %>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <div class="container main-content">
   
    
    <%= yield %>  
    
  </div>
  <%= render "layouts/footer" %>

</body>
</html>

app/views/lunches/create.js.erb
$(".date").val('');
$(".protein1").val('');
$(".protein2").val('');
$(".protein3").val('');
$(".accompaniment1").val('ARROZ BRANCO');
$(".accompaniment2").val('FEIJÃO');
$(".accompaniment3").val('ARROZ INTEGRAL');
$(".salada1").val('');
$(".salada2").val('');
$(".garnish").val('');
$(".dessert").val('');
$(".juice").val('');

swal("Almoço Cadastrado!");
$("#container_lunches").replace('<%= j render "form" %>');

app/views/lunches/edit.html.erb
<%= render 'form' %>

app/views/lunches/index.html.erb
<table class="table table-striped custab">
    <thead>
    
        <tr>
            <th>Date</th> 
            <th class="text-center">Action</th>
        </tr>
    </thead>
    <tbody>

        <% @lunches.each do |lunch| %>
            <tr>
                <td><%= link_to lunch.date, lunch %></td> 
                <td class="text-center">
                <%= link_to '<span class="glyphicon glyphicon-edit"></span> Edit'.html_safe, edit_lunch_path(lunch), :class => "btn btn-info btn-xs" %>
                <%= link_to '<span class="glyphicon glyphicon-remove"></span>Delete'.html_safe, lunch_path(lunch) , method: :delete ,data: { confirm: "Are you sure you want to delete this lunch?"}, class: "btn btn-danger btn-xs" %>
                </td>
            </tr>
          <% end %>

    </tbody>
</table>
<%= link_to '+ New Lunch', new_lunch_path, class: "btn btn-primary btn-xs pull-right" %>

app/views/lunches/new.html.erb
<%= render 'form' %>

app/views/pages/create.html.erb
<div class="container cont form-container">
	<div class="text-center">
		<button name="menu" checked  value="1" placeholder="Lunch" class="btn btn-blue active">Almoço</button>
		<button name="menu"  value="2" placeholder="Dinner" class="btn btn-blue">Janta</button>
	</div>
	<div>
		<div id="Menu1" class="desc">
		 
			<%= render :partial => "lunches/form", :locals => {:lunch => @lunches} %>
		</div>

		<div id="Menu2" class="desc" style="display: none;">

	 
			<%= render :partial => "dinners/form", :locals => {:dinner => @dinners} %>
		</div>

	</div>
</div>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>